"""add type column to projects

Revision ID: 18873bbb72e1
Revises: 
Create Date: 2026-01-01 19:28:56.064565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18873bbb72e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_videos_id'), table_name='scene_videos')
    op.drop_table('scene_videos')
    op.add_column('projects', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'type')
    op.create_table('scene_videos',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('src', sa.VARCHAR(), nullable=False),
    sa.Column('scene_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id')
    )
    op.create_index(op.f('ix_scene_videos_id'), 'scene_videos', ['id'], unique=False)
    # ### end Alembic commands ###
