"""Additional Columns for Timeline

Revision ID: 5621640951e9
Revises: 57d1c08f8c44
Create Date: 2026-02-28 18:58:23.798703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5621640951e9'
down_revision: Union[str, Sequence[str], None] = '57d1c08f8c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('cut_start', sa.Float(), nullable=True))
    op.add_column('music', sa.Column('cut_end', sa.Float(), nullable=True))
    op.add_column('music', sa.Column('layer', sa.Integer(), nullable=True))
    op.add_column('scenes', sa.Column('cut_start', sa.Float(), nullable=True))
    op.add_column('scenes', sa.Column('cut_end', sa.Float(), nullable=True))
    op.add_column('scenes', sa.Column('layer', sa.Integer(), nullable=True))
    op.add_column('voiceovers', sa.Column('cut_start', sa.Float(), nullable=True))
    op.add_column('voiceovers', sa.Column('cut_end', sa.Float(), nullable=True))
    op.add_column('voiceovers', sa.Column('layer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voiceovers', 'layer')
    op.drop_column('voiceovers', 'cut_end')
    op.drop_column('voiceovers', 'cut_start')
    op.drop_column('scenes', 'layer')
    op.drop_column('scenes', 'cut_end')
    op.drop_column('scenes', 'cut_start')
    op.drop_column('music', 'layer')
    op.drop_column('music', 'cut_end')
    op.drop_column('music', 'cut_start')
    # ### end Alembic commands ###
