"""Added Settings Table

Revision ID: 57d1c08f8c44
Revises: 5fa119cd1b76
Create Date: 2026-02-26 21:23:01.103851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d1c08f8c44'
down_revision: Union[str, Sequence[str], None] = '5fa119cd1b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('selected_tts_provider', sa.String(), nullable=True),
    sa.Column('selected_diffusion_provider', sa.String(), nullable=True),
    sa.Column('selected_llm_provider', sa.String(), nullable=True),
    sa.Column('tts_provider_settings', sa.Text(), nullable=True),
    sa.Column('diffusion_provider_settings', sa.Text(), nullable=True),
    sa.Column('llm_provider_settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
