"""fix_structure_switch_to_m2m

Revision ID: 7770d066dcde
Revises: 7f912b49ec36
Create Date: 2026-01-17 18:31:18.060495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7770d066dcde'
down_revision: Union[str, Sequence[str], None] = '7f912b49ec36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_images_package_association',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('images_package_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['images_package_id'], ['images_packages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_images_package_association')
    # ### end Alembic commands ###
