"""add images_package relation: images_packages + photo_dump_images tables + FK in projects

Revision ID: 7f912b49ec36
Revises: 18873bbb72e1
Create Date: 2026-01-01 23:44:10.359469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f912b49ec36'
down_revision: Union[str, Sequence[str], None] = '18873bbb72e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_dump_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('src', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['images_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_dump_images_package_id'), 'photo_dump_images', ['package_id'], unique=False)
    op.add_column('projects', sa.Column('images_package_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'projects', 'images_packages', ['images_package_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'images_package_id')
    op.drop_index(op.f('ix_photo_dump_images_package_id'), table_name='photo_dump_images')
    op.drop_table('photo_dump_images')
    op.drop_table('images_packages')
    # ### end Alembic commands ###
