"""Add Idea Column for Scene Image Table

Revision ID: 8e53ac19f5bf
Revises: a5cf027a520c
Create Date: 2026-03-08 19:18:06.354442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e53ac19f5bf'
down_revision: Union[str, Sequence[str], None] = 'a5cf027a520c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_images', sa.Column('idea', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene_images', 'idea')
    # ### end Alembic commands ###
