"""Add prompt and style settings columns for settings

Revision ID: a5cf027a520c
Revises: 5621640951e9
Create Date: 2026-03-03 01:54:21.822206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cf027a520c'
down_revision: Union[str, Sequence[str], None] = '5621640951e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('selected_style', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('styles', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('selected_script_generation_template', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('script_generation_templates', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'script_generation_templates')
    op.drop_column('settings', 'selected_script_generation_template')
    op.drop_column('settings', 'styles')
    op.drop_column('settings', 'selected_style')
    # ### end Alembic commands ###
