"""added start time and duration columns to music table

Revision ID: d2174f8e2aba
Revises: de3d6f66c6fa
Create Date: 2026-02-25 21:27:16.814660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2174f8e2aba'
down_revision: Union[str, Sequence[str], None] = 'de3d6f66c6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
