"""Add style column to scene images table

Revision ID: fa950cd327c8
Revises: 8e53ac19f5bf
Create Date: 2026-03-27 01:12:58.663310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa950cd327c8'
down_revision: Union[str, Sequence[str], None] = '8e53ac19f5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_images', sa.Column('style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene_images', 'style')
    # ### end Alembic commands ###
